# Generated by Django 3.2 on 2021-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surronshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(max_length=700, verbose_name='Описание'),
        ),
    ]
