# Generated by Django 3.2 on 2021-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surronshop', '0002_alter_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=255, verbose_name='Адрес'),
        ),
    ]
