# Generated by Django 3.2 on 2021-06-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surronshop', '0004_auto_20210624_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandMadeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('address', models.TextField(max_length=300, verbose_name='Адрес')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('phoneNumber', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('products', models.TextField(max_length=1000, verbose_name='Товары')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
            ],
            options={
                'verbose_name': 'Заказ в ручную',
                'verbose_name_plural': 'Заказы в ручную',
            },
        ),
    ]
