# Generated by Django 3.2 on 2021-06-25 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surronshop', '0006_rename_final_price_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='handmadeorder',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата заказа'),
        ),
    ]
