# Generated by Django 3.2 on 2021-06-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surronshop', '0007_handmadeorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Об', 'Обрабатывается'), ('Уп', 'Упаковывается'), ('От', 'Отправлен'), ('До', 'Доставлен')], default='Об', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
