# Generated by Django 3.2 on 2021-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surronshop', '0008_auto_20210626_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(to='surronshop.Order', verbose_name='Заказы'),
        ),
        migrations.AddField(
            model_name='handmadeorder',
            name='status',
            field=models.CharField(choices=[('Об', 'Обрабатывается'), ('Уп', 'Упаковывается'), ('От', 'Отправлен'), ('До', 'Доставлен')], default='Об', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
